apiVersion: apps/v1
kind: Deployment
metadata:
  name: gethelp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gethelp
  template:
    metadata:
      labels:
        app: gethelp
    spec:
      containers:
        - name: gethelp
          image: nginx:this-tag-doesnot-exist
          ports:
            - containerPort: 80

